
create extension if not exists "pgcrypto";
create table if not exists public.ea_profiles (id uuid primary key references auth.users(id) on delete cascade, created_at timestamptz default now(), name text not null, phone text, role text not null default 'Директор', is_active boolean default true);
create table if not exists public.ea_catalog (id uuid primary key default gen_random_uuid(), created_at timestamptz default now(), title text not null, price numeric default 0, category text default 'Тур', full_description text, media_links text, is_active boolean default true);
create table if not exists public.ea_clients (id uuid primary key default gen_random_uuid(), created_at timestamptz default now(), updated_at timestamptz default now(), name text not null, phone text not null, client_type text default 'Жаңа клиент', category text default 'Жылы', status text default 'Жаңа лид', source text default 'Instagram', approach_note text, followup_note text, next_action text, next_date date, whatsapp_template text, payment_requisites_sent boolean default false, note text);
create table if not exists public.ea_services (id uuid primary key default gen_random_uuid(), created_at timestamptz default now(), updated_at timestamptz default now(), client_id uuid references public.ea_clients(id) on delete set null, catalog_id uuid references public.ea_catalog(id) on delete set null, service_name text not null, client_name text not null, phone text not null, people_count int default 1, date_from date, date_to date, total_price numeric default 0, prepayment numeric default 0, paid numeric default 0, rest numeric default 0, payment_status text default 'Предоплата күтуде', status text default 'Тіркелді', note text);
create table if not exists public.ea_expenses (id uuid primary key default gen_random_uuid(), created_at timestamptz default now(), service_id uuid references public.ea_services(id) on delete set null, expense_date date default current_date, title text not null, category text default 'Басқа', amount numeric default 0, source text default 'Ручной', note text);
create table if not exists public.ea_marketing (id uuid primary key default gen_random_uuid(), created_at timestamptz default now(), channel text default 'Instagram', campaign text not null, content_type text default 'Reels', publish_date date, status text default 'Идея', budget numeric default 0, leads int default 0, sales int default 0, responsible text, note text);
create table if not exists public.ea_employees (id uuid primary key default gen_random_uuid(), created_at timestamptz default now(), name text not null, phone text, position text, salary_type text default 'Келісім', salary_amount numeric default 0, note text, is_active boolean default true);
create table if not exists public.ea_contracts (id uuid primary key default gen_random_uuid(), created_at timestamptz default now(), service_id uuid references public.ea_services(id) on delete set null, contract_no text, client_name text, phone text, contract_text text, status text default 'Дайындалды', sent_whatsapp boolean default false, note text);
create table if not exists public.ea_contract_settings (id int primary key default 1, company_name text default 'Ethno Altai', organizer_name text default '', phone text default '', kaspi text default '', address text default 'Катонқарағай, Шығыс Қазақстан', template text default 'Бұл келісім Ethno Altai туристік қызметін броньдау үшін жасалды. Клиент: {{client_name}}, телефон: {{phone}}, қызмет: {{service_name}}, мерзімі: {{date_from}} - {{date_to}}, жалпы сома: {{total_price}}, төленген: {{paid}}, қалғаны: {{rest}}. 30% предоплата броньды бекітеді. Маршрут ауа райына байланысты өзгеруі мүмкін.', updated_at timestamptz default now());
alter table public.ea_profiles enable row level security; alter table public.ea_catalog enable row level security; alter table public.ea_clients enable row level security; alter table public.ea_services enable row level security; alter table public.ea_expenses enable row level security; alter table public.ea_marketing enable row level security; alter table public.ea_employees enable row level security; alter table public.ea_contracts enable row level security; alter table public.ea_contract_settings enable row level security;
drop policy if exists "profiles_all" on public.ea_profiles; create policy "profiles_all" on public.ea_profiles for all to authenticated using (true) with check (true);
drop policy if exists "catalog_all" on public.ea_catalog; create policy "catalog_all" on public.ea_catalog for all to authenticated using (true) with check (true);
drop policy if exists "clients_all" on public.ea_clients; create policy "clients_all" on public.ea_clients for all to authenticated using (true) with check (true);
drop policy if exists "services_all" on public.ea_services; create policy "services_all" on public.ea_services for all to authenticated using (true) with check (true);
drop policy if exists "expenses_all" on public.ea_expenses; create policy "expenses_all" on public.ea_expenses for all to authenticated using (true) with check (true);
drop policy if exists "marketing_all" on public.ea_marketing; create policy "marketing_all" on public.ea_marketing for all to authenticated using (true) with check (true);
drop policy if exists "employees_all" on public.ea_employees; create policy "employees_all" on public.ea_employees for all to authenticated using (true) with check (true);
drop policy if exists "contracts_all" on public.ea_contracts; create policy "contracts_all" on public.ea_contracts for all to authenticated using (true) with check (true);
drop policy if exists "contract_settings_all" on public.ea_contract_settings; create policy "contract_settings_all" on public.ea_contract_settings for all to authenticated using (true) with check (true);
insert into public.ea_catalog (title, price, category, full_description, media_links) values
('2 күндік тур',85000,'Тур','1-күн: Өскеменнен шығу, Бұхтырма, Катонқарағай тауы, киіз үй, кешкі ас, костер. 2-күн: Өрел сарқырамасы, Жамбыл көпірі, Берел мұражайы, Берел көпірі, қайту.',''),
('3 күндік тур',120000,'Тур','Рахман, Берел, Маймер, Сібина, киіз үй, табиғат, фото-тоқтау, этно атмосфера.',''),
('4 күндік — Тау + Ат',160000,'Тур','2600 м көру алаңы, атпен тур, үңгір, петроглиф, орман жолдары, киіз үй.',''),
('4 күндік — Этно + Relax',180000,'Тур','Пантовая ванна, форель, баня, марал, Катон өнімдері, этно демалыс.',''),
('Киіз үй қону',20000,'Қону','2 адамнан бастап. Ыдыс-аяқ, душ, таза төсек, отын кіреді.',''),
('Индивидуальный / лечебный тур',0,'Жеке тур','Маршрут жеке құрылады. Домик, киіз үй, лечебный формат, VIP қызмет — келісім бойынша.','') on conflict do nothing;
insert into public.ea_contract_settings (id) values (1) on conflict (id) do nothing;
